sudo: false

language: php

php:
    - 8.0
    - 7.4
    - 7.3

install:
    - make vendor/installed
    - wget -O phive.phar https://phar.io/releases/phive.phar
    - make tools/installed PHIVE_CMD="php phive.phar"

script:
    - make test
